//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Cake Contributions")]
[assembly: AssemblyProduct("Cake.AliaSql")]
[assembly: AssemblyVersion("0.4.1")]
[assembly: AssemblyFileVersion("0.4.1")]
[assembly: AssemblyInformationalVersion("0.4.1")]
[assembly: AssemblyCopyright("Copyright © Cake Contributions 2016 - Present")]
